// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260306144440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("dotnet_store.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Price = 30000.0,
                            ProductName = "Apple Watch 6"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = false,
                            Price = 35000.0,
                            ProductName = "Apple Watch 7"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Price = 40000.0,
                            ProductName = "Apple Watch 8"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Price = 45000.0,
                            ProductName = "Apple Watch 9"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = false,
                            Price = 50000.0,
                            ProductName = "Apple Watch 10"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Price = 55000.0,
                            ProductName = "Apple Watch 11"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
