// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260307143354_UpdateProductEntity")]
    partial class UpdateProductEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("dotnet_store.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Homepage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Explanation = " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ea, debitis blanditiis corrupti ducimus numquam saepe praesentium est sed! Repellendus architecto sit suscipit nobis at veritatis illum rem placeat debitis eius.",
                            Homepage = true,
                            Image = "1.jpeg",
                            IsActive = true,
                            Price = 30000.0,
                            ProductName = "Apple Watch 6"
                        },
                        new
                        {
                            Id = 2,
                            Explanation = " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ea, debitis blanditiis corrupti ducimus numquam saepe praesentium est sed! Repellendus architecto sit suscipit nobis at veritatis illum rem placeat debitis eius.",
                            Homepage = true,
                            Image = "2.jpeg",
                            IsActive = false,
                            Price = 35000.0,
                            ProductName = "Apple Watch 7"
                        },
                        new
                        {
                            Id = 3,
                            Explanation = " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ea, debitis blanditiis corrupti ducimus numquam saepe praesentium est sed! Repellendus architecto sit suscipit nobis at veritatis illum rem placeat debitis eius.",
                            Homepage = true,
                            Image = "3.jpeg",
                            IsActive = true,
                            Price = 40000.0,
                            ProductName = "Apple Watch 8"
                        },
                        new
                        {
                            Id = 4,
                            Explanation = " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ea, debitis blanditiis corrupti ducimus numquam saepe praesentium est sed! Repellendus architecto sit suscipit nobis at veritatis illum rem placeat debitis eius.",
                            Homepage = false,
                            Image = "4.jpeg",
                            IsActive = true,
                            Price = 45000.0,
                            ProductName = "Apple Watch 9"
                        },
                        new
                        {
                            Id = 5,
                            Explanation = " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ea, debitis blanditiis corrupti ducimus numquam saepe praesentium est sed! Repellendus architecto sit suscipit nobis at veritatis illum rem placeat debitis eius.",
                            Homepage = true,
                            Image = "5.jpeg",
                            IsActive = false,
                            Price = 50000.0,
                            ProductName = "Apple Watch 10"
                        },
                        new
                        {
                            Id = 6,
                            Explanation = " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ea, debitis blanditiis corrupti ducimus numquam saepe praesentium est sed! Repellendus architecto sit suscipit nobis at veritatis illum rem placeat debitis eius.",
                            Homepage = true,
                            Image = "6.jpeg",
                            IsActive = false,
                            Price = 55000.0,
                            ProductName = "Apple Watch 11"
                        },
                        new
                        {
                            Id = 7,
                            Explanation = " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ea, debitis blanditiis corrupti ducimus numquam saepe praesentium est sed! Repellendus architecto sit suscipit nobis at veritatis illum rem placeat debitis eius.",
                            Homepage = false,
                            Image = "7.jpeg",
                            IsActive = true,
                            Price = 60000.0,
                            ProductName = "Apple Watch 12"
                        },
                        new
                        {
                            Id = 8,
                            Explanation = " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ea, debitis blanditiis corrupti ducimus numquam saepe praesentium est sed! Repellendus architecto sit suscipit nobis at veritatis illum rem placeat debitis eius.",
                            Homepage = true,
                            Image = "8.jpeg",
                            IsActive = true,
                            Price = 65000.0,
                            ProductName = "Apple Watch 13"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
